# -*- coding: utf-8 -*-
"""3_Taste4Privacy_instanddems.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cr3l9Z5aVUKVu32koEgipZ2E2fVWJkdL
"""

import numpy as np
import pandas as pd
import os
from matplotlib.patches import Patch

import warnings
warnings.filterwarnings("ignore")

import matplotlib.pyplot as plt
import seaborn as sns

from statsmodels.miscmodels.ordinal_model import OrderedModel

"""# Data"""

# read in df_all
df_all = pd.read_csv('filepath.csv')

"""# Taste for privacy by context and demographics"""

CONTEXTS = [
    "TP_Gov","TP_Police","TP_Friend","TP_Relative","TP_Employer","TP_Medical",
    "TP_Financial","TP_Neighbor","TP_Acquaintance","TP_Co_worker","TP_School",
    "TP_Researcher","TP_Platform","TP_NonProf","TP_Company_cust","TP_Company_notcust","TP_Stranger"
]
id_col = "ID"

"""#Is taste for privacy shaped by both who you are? does the prefence of contexts change by demographics?

#Mean difference bootstraps
"""

# Plot mean discomfort differences between two groups
# Positive = Group 1 MORE uncomfortable

def plot_mean_difference(df, contexts, demo_col1, demo_col2, group1_name, group2_name,
                        n_bootstrap=10000, save_path=None):

    df_g1 = df[df[demo_col1] == 1]
    df_g2 = df[df[demo_col2] == 1]

    # Bootstrap mean differences
    np.random.seed(42)
    mean_diffs = {ctx: [] for ctx in contexts}

    for i in range(n_bootstrap):
        boot_g1 = df_g1.sample(n=len(df_g1), replace=True)
        boot_g2 = df_g2.sample(n=len(df_g2), replace=True)

        for ctx in contexts:
            mean_g1 = boot_g1[ctx].mean()
            mean_g2 = boot_g2[ctx].mean()
            mean_diffs[ctx].append(mean_g1 - mean_g2)

    # Calculate statistics
    results = []
    for ctx in contexts:
        diffs = mean_diffs[ctx]
        results.append({
            'institution': ctx.replace('TP_', ''),
            'mean_diff': np.mean(diffs),
            'ci_lo': np.percentile(diffs, 2.5),
            'ci_hi': np.percentile(diffs, 97.5),
            'significant': not (np.percentile(diffs, 2.5) <= 0 <= np.percentile(diffs, 97.5)),
            'g1_mean': df_g1[ctx].mean(),
            'g2_mean': df_g2[ctx].mean()
        })

    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values('mean_diff', key=abs, ascending=False)

    # Plot
    fig, ax = plt.subplots(figsize=(10, 8))
    y_pos = np.arange(len(results_df))

    colors = ['steelblue' if sig else 'lightgray' for sig in results_df['significant']]
    ax.barh(y_pos, results_df['mean_diff'], color=colors, alpha=0.7)

    xerr = np.abs(results_df[['ci_lo', 'ci_hi']].values.T - results_df['mean_diff'].values)
    ax.errorbar(results_df['mean_diff'], y_pos, xerr=xerr,
                fmt='none', color='black', capsize=3, linewidth=1)

    ax.axvline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(results_df['institution'])
    ax.set_xlabel(f'Mean Discomfort Difference ({group1_name} - {group2_name})\nPositive = {group1_name} more uncomfortable')
    ax.set_ylabel('Institution')

    legend_elements = [
        Patch(facecolor='steelblue', alpha=0.7, label='Significant (95% CI excludes 0)'),
        Patch(facecolor='lightgray', alpha=0.7, label='Not significant')
    ]
    ax.legend(handles=legend_elements, loc='best', fontsize=9)
    ax.grid(True, alpha=0.3, axis='x')
    plt.tight_layout()

    return fig, results_df

"""##gender"""

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Gender_Woman', 'Dem_Gender_Man',
    'Women', 'Men'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Gender_Woman', 'Dem_Gender_Other',
    'Women', 'Non-binary'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Gender_Man', 'Dem_Gender_Other',
    'Man', 'Non-binary'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Race_White', 'Dem_Race_Mixed',
    'White', 'Multi-racial'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Race_White', 'Dem_Race_POC',
    'White', 'Person of Color'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Race_Mixed', 'Dem_Race_POC',
    'Multi-racial', 'Person of Color'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_FirtsGen_Yes', 'Dem_FirtsGen_No',
    'First-generation', 'Not First-generation'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Therapy_Yes', 'Dem_Therapy_No',
    'Therapy Yes', 'Therapy No'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'ACES_Yes', 'ACES_No',
    'ACES Yes', 'ACES No'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_straight', 'Dem_Sexual_Orientation_Bisexual',
    'Sexual Orientation: Straight', 'Sexual Orientation: Bi-sexual'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_Gay', 'Dem_Sexual_Orientation_Bisexual',
    'Sexual Orientation: Gay', 'Sexual Orientation: Bi-sexual'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_other', 'Dem_Sexual_Orientation_Bisexual',
    'Sexual Orientation: Other', 'Sexual Orientation: Bi-sexual'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_straight', 'Dem_Sexual_Orientation_Gay',
    'Sexual Orientation: Straight', 'Sexual Orientation: Gay'
)

fig, results_df = plot_mean_difference(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_straight', 'Dem_Sexual_Orientation_other',
    'Sexual Orientation: Straight', 'Sexual Orientation: Other'
)

"""#ACES Dose"""

def ace_trend_forest(df, contexts, ace_col="ACES_Compound", y_min=0, y_max=7,
                     save_path=None, dpi=300, show=True):
    rows = []
    for ctx in contexts:
        d = df[[ctx, ace_col]].dropna()
        # OrderedModel needs integer ordered responses
        y = d[ctx].astype(int).clip(y_min, y_max)
        X = d[[ace_col]]
        mod = OrderedModel(y, X, distr="logit")
        res = mod.fit(method="bfgs", disp=False)
        beta = res.params[ace_col]
        lo, hi = res.conf_int().loc[ace_col]
        rows.append({"context": ctx, "beta": beta, "lo": lo, "hi": hi, "n": len(d)})

    ef = pd.DataFrame(rows).sort_values("beta")
    y = np.arange(len(ef))

    plt.figure(figsize=(8, 0.45*len(ef)+1.5))
    # color significant effects
    sig = (ef["lo"]>0) | (ef["hi"]<0)
    colors = np.where(sig, "tab:orange", "0.6")

    plt.errorbar(ef["beta"], y, xerr=[ef["beta"]-ef["lo"], ef["hi"]-ef["beta"]],
                 fmt="o", capsize=3, elinewidth=1, ecolor="black", mfc="white")
    for i,c in enumerate(colors):
        plt.plot([ef["lo"].iloc[i], ef["hi"].iloc[i]], [y[i], y[i]], color=c, linewidth=4, alpha=0.6)

    plt.axvline(0, color="black", lw=1)
    plt.yticks(y, ef["context"])
    plt.xlabel("Ordinal logit coefficient for ACE count (per +1 ACE)\n(>0 = more uncomfortable with more ACEs)")
    plt.tight_layout()

"""#Rank Difference Approach"""

# Bootstrap rankings for a single group
def bootstrap_rankings_single_group(df, contexts, n_bootstrap=10000, random_state=42):
    np.random.seed(random_state)
    boot_ranks = {ctx: [] for ctx in contexts}

    for i in range(n_bootstrap):
        boot_sample = df.sample(n=len(df), replace=True)
        means = {ctx: boot_sample[ctx].mean() for ctx in contexts}
        sorted_contexts = sorted(means.items(), key=lambda x: x[1], reverse=True)

        for rank, (ctx, _) in enumerate(sorted_contexts, start=1):
            boot_ranks[ctx].append(rank)

    return boot_ranks

# Bootstrap comparison of institution rankings between two demographic groups

def bootstrap_demographic_comparison(df, contexts, demo_col1, demo_col2, group1_name, group2_name,
                                     n_bootstrap=10000, random_state=42):
    np.random.seed(random_state)

    df_g1 = df[df[demo_col1] == 1].copy()
    df_g2 = df[df[demo_col2] == 1].copy()

    print(f"{group1_name}: n={len(df_g1)}")
    print(f"{group2_name}: n={len(df_g2)}")

    rank_diffs = {ctx: [] for ctx in contexts}

    for i in range(n_bootstrap):
        boot_g1 = df_g1.sample(n=len(df_g1), replace=True)
        boot_g2 = df_g2.sample(n=len(df_g2), replace=True)

        means_g1 = {ctx: boot_g1[ctx].mean() for ctx in contexts}
        means_g2 = {ctx: boot_g2[ctx].mean() for ctx in contexts}

        sorted_g1 = sorted(means_g1.items(), key=lambda x: x[1], reverse=True)
        sorted_g2 = sorted(means_g2.items(), key=lambda x: x[1], reverse=True)

        ranks_g1 = {ctx: rank for rank, (ctx, _) in enumerate(sorted_g1, start=1)}
        ranks_g2 = {ctx: rank for rank, (ctx, _) in enumerate(sorted_g2, start=1)}
        for ctx in contexts:
            rank_diffs[ctx].append(ranks_g2[ctx] - ranks_g1[ctx])

    results = []
    for ctx in contexts:
        diffs = rank_diffs[ctx]
        results.append({
            'institution': ctx.replace('TP_', ''),
            'rank_diff_mean': np.mean(diffs),
            'rank_diff_lo': np.percentile(diffs, 2.5),
            'rank_diff_hi': np.percentile(diffs, 97.5),
            'significant': not (np.percentile(diffs, 2.5) <= 0 <= np.percentile(diffs, 97.5))
        })

    results_df = pd.DataFrame(results)
    results_df = results_df.sort_values('rank_diff_mean', key=abs, ascending=False)

    return results_df, df_g1, df_g2

# Plot ranking with CIs for a single group

def plot_single_group_ranking(df_group, contexts, group_name, save_path=None):
    boot_ranks = bootstrap_rankings_single_group(df_group, contexts, n_bootstrap=10000)

    rank_table = []
    for ctx in contexts:
        ranks = boot_ranks[ctx]
        rank_table.append({
            'institution': ctx.replace('TP_', ''),
            'rank_mean': np.mean(ranks),
            'rank_lo': np.percentile(ranks, 2.5),
            'rank_hi': np.percentile(ranks, 97.5),
            'actual_mean': df_group[ctx].mean()
        })

    rank_table = pd.DataFrame(rank_table)
    rank_table = rank_table.sort_values('rank_mean')
    rank_table.index = rank_table['institution']

    # Create plot
    fig, ax = plt.subplots(figsize=(8, 6))
    y = np.arange(len(rank_table))

    ax.hlines(y, rank_table["rank_lo"], rank_table["rank_hi"], color='steelblue', alpha=0.6)
    ax.plot(rank_table["rank_mean"], y, "o", color='steelblue', markersize=8)

    ax.set_yticks(y)
    ax.set_yticklabels(rank_table.index)
    ax.invert_xaxis()
    ax.set_xlabel("Bootstrap rank (95% CI) — lower = more uncomfortable")
    ax.set_title(f"Rank robustness — {group_name}")
    ax.grid(True, alpha=0.3, axis='x')
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')

    return fig, rank_table

# Create bar plot showing rank differences between groups

def plot_rank_diff_bar(results_df, group1_name, group2_name, save_path=None):
    fig, ax = plt.subplots(figsize=(10, 8))
    y_pos = np.arange(len(results_df))

    colors = ['steelblue' if sig else 'lightgray' for sig in results_df['significant']]
    ax.barh(y_pos, results_df['rank_diff_mean'], color=colors, alpha=0.7)

    xerr = np.abs(results_df[['rank_diff_lo', 'rank_diff_hi']].values.T - results_df['rank_diff_mean'].values)
    ax.errorbar(results_df['rank_diff_mean'], y_pos, xerr=xerr,
                fmt='none', color='black', capsize=3, linewidth=1)

    ax.axvline(0, color='black', linestyle='--', linewidth=1, alpha=0.5)
    ax.set_yticks(y_pos)
    ax.set_yticklabels(results_df['institution'])
    ax.set_xlabel(f'Rank Difference ({group1_name} - {group2_name})\nPositive = {group1_name} more uncomfortable')
    ax.set_ylabel('Institution')
    ax.set_title(f'Privacy Ranking Differences: {group1_name} vs {group2_name}',
                 fontweight='bold', fontsize=12)

    legend_elements = [
        Patch(facecolor='steelblue', alpha=0.7, label='Significant (95% CI excludes 0)'),
        Patch(facecolor='lightgray', alpha=0.7, label='Not significant')
    ]
    ax.legend(handles=legend_elements, loc='best', fontsize=9)
    ax.grid(True, alpha=0.3, axis='x')
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')

    return fig, ax

def analyze_demographic_pair(df, contexts, demo_col1, demo_col2, group1_name, group2_name,
                             output_dir=None, n_bootstrap=10000):
    # Get data for each group
    df_g1 = df[df[demo_col1] == 1]
    df_g2 = df[df[demo_col2] == 1]

    # Individual group rankings
    print(f"\n1. {group1_name} Rankings")
    print("-"*70)
    save_path1 = f"{output_dir}/{group1_name.lower()}_rank_ci.pdf" if output_dir else None
    fig1, rank_table1 = plot_single_group_ranking(df_g1, contexts, group1_name, save_path1)
    print(rank_table1[['rank_mean', 'rank_lo', 'rank_hi', 'actual_mean']])

    print(f"\n2. {group2_name} Rankings")
    print("-"*70)
    save_path2 = f"{output_dir}/{group2_name.lower()}_rank_ci.pdf" if output_dir else None
    fig2, rank_table2 = plot_single_group_ranking(df_g2, contexts, group2_name, save_path2)
    print(rank_table2[['rank_mean', 'rank_lo', 'rank_hi', 'actual_mean']])

    # Comparison
    print(f"\n3. Comparing {group1_name} vs {group2_name}")
    print("-"*70)
    results_df, _, _ = bootstrap_demographic_comparison(
        df, contexts, demo_col1, demo_col2, group1_name, group2_name, n_bootstrap=n_bootstrap
    )
    print("\nRank Differences:")
    print(results_df[['institution', 'rank_diff_mean', 'rank_diff_lo', 'rank_diff_hi', 'significant']])

    # Rank difference bar plot
    save_path3 = f"{output_dir}/{group1_name.lower()}_{group2_name.lower()}_rankdiff.pdf" if output_dir else None
    fig3, ax3 = plot_rank_diff_bar(results_df, group1_name, group2_name, save_path3)

    return {
        'results_df': results_df,
        'rank_table_g1': rank_table1,
        'rank_table_g2': rank_table2
    }

"""##gender"""

output_dir = '/filepath'

# men vs women
menwomen_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Gender_Woman', 'Dem_Gender_Man',
    'Women', 'Men',
    output_dir=output_dir,
    n_bootstrap=10000
)

othermen_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Gender_Other', 'Dem_Gender_Man',
    'Non-binary', 'Men',
    output_dir=output_dir,
    n_bootstrap=10000
)

womemenother_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Gender_Other', 'Dem_Gender_Woman',
    'Non-binary', 'Woman',
    output_dir=output_dir,
    n_bootstrap=10000
)

therapy_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Therapy_Yes', 'Dem_Therapy_No',
    'Therapy Yes', 'Therapy No',
    output_dir=output_dir,
    n_bootstrap=10000
)

firtgen_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_FirtsGen_Yes', 'Dem_FirtsGen_No',
    'First Generation Yes', 'Not First Generation',
    output_dir=output_dir,
    n_bootstrap=10000
)

whitepoc_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Race_White', 'Dem_Race_POC',
    'White', 'Person of Color',
    output_dir=output_dir,
    n_bootstrap=10000
)

mixedpoc_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Race_Mixed', 'Dem_Race_POC',
    'Multi-racial', 'Person of Color',
    output_dir=output_dir,
    n_bootstrap=10000
)

mixedwhite_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Race_Mixed', 'Dem_Race_White',
    'Multi-racial', 'White',
    output_dir=output_dir,
    n_bootstrap=10000
)

straightgay_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_straight', 'Dem_Sexual_Orientation_Gay',
    'Sexual Orientation: Straight', 'Sexual Orientation: Gay',
    output_dir=output_dir,
    n_bootstrap=10000
)

straightbi_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_straight', 'Dem_Sexual_Orientation_Bisexual',
    'Sexual Orientation: Straight', 'Sexual Orientation: Bi-sexual',
    output_dir=output_dir,
    n_bootstrap=10000
)

straightother_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_straight', 'Dem_Sexual_Orientation_other',
    'Sexual Orientation: Straight', 'Sexual Orientation: Other',
    output_dir=output_dir,
    n_bootstrap=10000
)

gaybi_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_Bisexual', 'Dem_Sexual_Orientation_Gay',
    'Sexual Orientation: Bi-sexual', 'Sexual Orientation: Gay',
    output_dir=output_dir,
    n_bootstrap=10000
)

otherbi_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'Dem_Sexual_Orientation_Bisexual', 'Dem_Sexual_Orientation_other',
    'Sexual Orientation: Bi-sexual', 'Sexual Orientation: Other',
    output_dir=output_dir,
    n_bootstrap=10000
)

acesyesno_results = analyze_demographic_pair(
    df_all, CONTEXTS,
    'ACES_Yes', 'ACES_No',
    'ACES Yes', 'ACES No',
    output_dir=output_dir,
    n_bootstrap=10000
)