# -*- coding: utf-8 -*-
"""4_Taste4Privacy-instanddems_cirlceplots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feqiSJ_J5776RdmvAspKmafbT59M-I0x
"""

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import Patch

# Set style for publication-quality plots
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")

"""# New Section

# Data
"""

# read in df_all
df_all = pd.read_csv('filepath.csv')

#change colum name 	Unnamed: 0 to ID
df_all = df_all.rename(columns={'Unnamed: 0': 'ID'})

"""#circles of trust visualization"""

# Create circular bar chart with concentric rings showing Likert response distributions.
# Arc length represents mean discomfort, with stacked segments showing proportion breakdown.

def create_circular_stacked_bar_chart(df, demographic_var, institution_cols,
                                      value=1, label=None, figsize=(12, 12),
                                      global_order=None):
    if label is None:
        label = f"{demographic_var}={value}"

    if global_order is None:
        global_means = {}
        for inst in institution_cols:
            global_means[inst] = df[inst].dropna().mean()
        # Sort institutions by global mean (lowest to highest = most to least trusted)
        global_order = sorted(global_means.keys(), key=lambda x: global_means[x])

    # Filter data for the group
    group_df = df[df[demographic_var] == value]

    # Calculate statistics and proportions for each institution
    stats = []
    for inst in institution_cols:
        inst_data = group_df[inst].dropna()

        # Calculate mean for arc length
        mean_val = inst_data.mean()

        # Calculate proportion of each Likert response (1-7)
        proportions = []
        for likert_val in range(1, 8):
            prop = (inst_data == likert_val).sum() / len(inst_data)
            proportions.append(prop)

        stats.append({
            'institution': inst,
            'mean': mean_val,
            'proportions': proportions,
            'n': len(inst_data)
        })

    stats_df = pd.DataFrame(stats)

    # Sort by global order
    stats_df['sort_order'] = stats_df['institution'].map({inst: i for i, inst in enumerate(global_order)})
    stats_df = stats_df.sort_values('sort_order').reset_index(drop=True)
    stats_df = stats_df.drop('sort_order', axis=1)

    max_value_full_ring = 7  # Maximum Likert score
    data_len = len(stats_df)

    # Color scheme for Likert responses (1=green to 7=red)
    likert_colors = ['#22c55e', '#84cc16', '#eab308', '#f97316', '#ef4444', '#dc2626', '#991b1b']

    # Create labels with institution name and mean value
    ring_labels = [f"   {row['institution'].replace('TP_', '').replace('_', ' ')} ({row['mean']:.1f})   "
                   for _, row in stats_df.iterrows()]

    fig = plt.figure(figsize=figsize, linewidth=2,
                     edgecolor='#cccccc',
                     facecolor='white')

    # Add title
    fig.text(0.5, 0.95, f'Comfort Sharing PII by Institution: {label}',
             ha='center', fontsize=20, fontweight='bold', color='#2c3e50')

    rect = [0.1, 0.1, 0.8, 0.8]

    # Add axis for radial backgrounds
    ax_polar_bg = fig.add_axes(rect, polar=True, frameon=False)
    ax_polar_bg.set_theta_zero_location('N')
    ax_polar_bg.set_theta_direction(1)

    # Loop through each entry and plot a grey ring for background
    for i in range(data_len):
        ax_polar_bg.barh(i, max_value_full_ring * 1.5 * np.pi / max_value_full_ring,
                         color='lightgrey',
                         alpha=0.3,
                         edgecolor='white',
                         linewidth=2)

    # Hide all axis items
    ax_polar_bg.axis('off')

    # Add axis for radial chart for each institution
    ax_polar = fig.add_axes(rect, polar=True, frameon=False)
    ax_polar.set_theta_zero_location('N')
    ax_polar.set_theta_direction(1)
    ax_polar.set_rgrids(range(data_len),
                        labels=ring_labels,
                        angle=0,
                        fontsize=11, fontweight='bold',
                        color='#2c3e50', verticalalignment='center')

    # Loop through each institution and create stacked colored segments
    for i, row in stats_df.iterrows():
        mean = row['mean']
        proportions = row['proportions']

        # Total arc length based on mean (same as before)
        total_arc_length = mean * 1.5 * np.pi / max_value_full_ring

        # Calculate cumulative angles for stacking
        cumulative_angle = 0

        for likert_idx, prop in enumerate(proportions):
            if prop > 0:  # Only draw if there's a proportion
                # Width of this segment = proportion of total arc length
                segment_width = prop * total_arc_length

                # Draw this segment
                ax_polar.barh(i, segment_width,
                              left=cumulative_angle,
                              color=likert_colors[likert_idx],
                              alpha=0.85,
                              height=0.8,
                              edgecolor='white',
                              linewidth=2)

                cumulative_angle += segment_width

    # Hide all grid elements
    ax_polar.grid(False)
    ax_polar.tick_params(axis='both', left=False, bottom=False,
                         labelbottom=False, labelleft=True)

    # Add center text
    ax_polar.text(0, -1, '',
                  ha='center', va='center', fontsize=13, fontweight='bold',
                  color='#2c3e50',
                  bbox=dict(boxstyle='round,pad=0.5', facecolor='white',
                           edgecolor='#95a5a6', linewidth=2, alpha=0.9))

    # Create legend for Likert scale
    legend_labels = ['1 (Very comfortable)', '2', '3', '4 (Neutral)', '5', '6', '7 (Very uncomfortable)']
    legend_elements = [Patch(facecolor=likert_colors[i], edgecolor='white',
                            label=legend_labels[i])
                      for i in range(7)]

    ax_polar.legend(handles=legend_elements, loc='center left', bbox_to_anchor=(1.1, 0.5),
                   frameon=True, title='Likert Scale', title_fontsize=11, fontsize=9)

    return fig

# Create circular bar chart for entire population (no demographic filtering).
# Arc length represents mean discomfort, with stacked segments showing proportion breakdown.

def create_circular_stacked_bar_chart_all(df, institution_cols,
                                          label='All Participants',
                                          figsize=(12, 12)):

    # Calculate statistics and proportions for each institution
    stats = []
    for inst in institution_cols:
        inst_data = df[inst].dropna()

        # Calculate mean for arc length
        mean_val = inst_data.mean()

        # Calculate proportion of each Likert response (1-7)
        proportions = []
        for likert_val in range(1, 8):
            prop = (inst_data == likert_val).sum() / len(inst_data)
            proportions.append(prop)

        stats.append({
            'institution': inst,
            'mean': mean_val,
            'proportions': proportions,
            'n': len(inst_data)
        })

    stats_df = pd.DataFrame(stats)

    # Sort by mean (most trusted to least trusted)
    stats_df = stats_df.sort_values('mean').reset_index(drop=True)

    max_value_full_ring = 7  # Maximum Likert score
    data_len = len(stats_df)

    # Color scheme for Likert responses (1=green to 7=red)
    likert_colors = ['#22c55e', '#84cc16', '#eab308', '#f97316', '#ef4444', '#dc2626', '#991b1b']

    # Create labels with institution name and mean value
    ring_labels = [f"   {row['institution'].replace('TP_', '').replace('_', ' ')} ({row['mean']:.1f})   "
                   for _, row in stats_df.iterrows()]

    # Begin creating the figure
    fig = plt.figure(figsize=figsize, linewidth=2,
                     edgecolor='#cccccc',
                     facecolor='white')

    rect = [0.1, 0.1, 0.8, 0.8]

    # Add axis for radial backgrounds
    ax_polar_bg = fig.add_axes(rect, polar=True, frameon=False)
    ax_polar_bg.set_theta_zero_location('N')
    ax_polar_bg.set_theta_direction(1)

    # Loop through each entry and plot a grey ring for background
    for i in range(data_len):
        ax_polar_bg.barh(i, max_value_full_ring * 1.5 * np.pi / max_value_full_ring,
                         color='lightgrey',
                         alpha=0.3,
                         edgecolor='white',
                         linewidth=2)

    # Hide all axis items
    ax_polar_bg.axis('off')

    # Add axis for radial chart for each institution
    ax_polar = fig.add_axes(rect, polar=True, frameon=False)
    ax_polar.set_theta_zero_location('N')
    ax_polar.set_theta_direction(1)
    ax_polar.set_rgrids(range(data_len),
                        labels=ring_labels,
                        angle=0,
                        fontsize=11, fontweight='bold',
                        color='#2c3e50', verticalalignment='center')

    # Loop through each institution and create stacked colored segments
    for i, row in stats_df.iterrows():
        mean = row['mean']
        proportions = row['proportions']

        # Total arc length based on mean
        total_arc_length = mean * 1.5 * np.pi / max_value_full_ring

        # Calculate cumulative angles for stacking
        cumulative_angle = 0

        for likert_idx, prop in enumerate(proportions):
            if prop > 0:  # Only draw if there's a proportion
                # Width of this segment = proportion of total arc length
                segment_width = prop * total_arc_length

                # Draw this segment
                ax_polar.barh(i, segment_width,
                              left=cumulative_angle,
                              color=likert_colors[likert_idx],
                              alpha=0.85,
                              height=0.8,
                              edgecolor='white',
                              linewidth=2)

                cumulative_angle += segment_width

    # Hide all grid elements
    ax_polar.grid(False)
    ax_polar.tick_params(axis='both', left=False, bottom=False,
                         labelbottom=False, labelleft=True)

    # Add center text
    ax_polar.text(0, -1, '',
                  ha='center', va='center', fontsize=13, fontweight='bold',
                  color='#2c3e50',
                  bbox=dict(boxstyle='round,pad=0.5', facecolor='white',
                           edgecolor='#95a5a6', linewidth=2, alpha=0.9))

    # Create legend for Likert scale
    legend_labels = ['1 (Very comfortable)', '2', '3', '4 (Neutral)', '5', '6', '7 (Very uncomfortable)']
    legend_elements = [Patch(facecolor=likert_colors[i], edgecolor='white',
                            label=legend_labels[i])
                      for i in range(7)]

    ax_polar.legend(handles=legend_elements, loc='center left', bbox_to_anchor=(1.1, 0.5),
                   frameon=True, title='Likert Scale', title_fontsize=13, fontsize=11)

    return fig

# Create visualization for entire population
fig = create_circular_stacked_bar_chart_all(df_all, institution_cols,
                                            label='All Participants')
plt.show()

# Visualize Women
fig = create_circular_stacked_bar_chart(df_all, 'Dem_Gender_Woman', institution_cols,
                                        value=1, label='Women')

# Visualize Men
fig = create_circular_stacked_bar_chart(df_all, 'Dem_Gender_Man', institution_cols,
                                        value=1, label='Men')

# Visualize Men
fig = create_circular_stacked_bar_chart(df_all, 'Dem_Gender_Other', institution_cols,
                                        value=1, label='Non-binary')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Race_White', institution_cols,
                                        value=1, label='Race White')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Race_Mixed', institution_cols,
                                        value=1, label='Race - Multiracial')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Race_POC', institution_cols,
                                        value=1, label='Race Person of Color')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_FirtsGen_Yes', institution_cols,
                                        value=1, label='First Generation')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_FirtsGen_No', institution_cols,
                                        value=1, label='Not First Generation')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Sexual_Orientation_straight', institution_cols,
                                        value=1, label='Sexual Orientation: Straight')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Sexual_Orientation_Bisexual', institution_cols,
                                        value=1, label='Sexual Orientation: Bi-sexual')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Sexual_Orientation_Gay', institution_cols,
                                        value=1, label='Sexual Orientation: Gay')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Sexual_Orientation_other', institution_cols,
                                        value=1, label='Sexual Orientation: Other')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Therapy_Yes', institution_cols,
                                        value=1, label='Therapy Yes')

fig = create_circular_stacked_bar_chart(df_all, 'Dem_Therapy_No', institution_cols,
                                        value=1, label='Therapy No')

fig = create_circular_stacked_bar_chart(df_all, 'ACES_No', institution_cols,
                                        value=1, label='ACES No')

fig = create_circular_stacked_bar_chart(df_all, 'ACES_Yes', institution_cols,
                                        value=1, label='ACES Yes')

"""#"""